# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IEvx5loxV2sWXYpNizww7SD6Yu5FkBeQ
"""

import streamlit as st
import yfinance as yf
import plotly.graph_objs as go

# Set page title
st.title("📈 Stock Market Analysis")

# Input for stock ticker
ticker = st.text_input("Enter Stock Ticker (e.g., AAPL)", "AAPL")

if ticker:
    # Fetch stock data
    stock = yf.Ticker(ticker)
    hist = stock.history(period="1y")

    # Display stock chart
    st.subheader(f"{ticker} Price Chart")
    fig = go.Figure(data=[go.Candlestick(
        x=hist.index,
        open=hist['Open'],
        high=hist['High'],
        low=hist['Low'],
        close=hist['Close'],
        increasing_line_color='green',
        decreasing_line_color='red'
    )])
    st.plotly_chart(fig)

    # Display financial metrics
    st.subheader("📊 Financial Metrics")
    info = stock.info
    metrics = {
        "P/E Ratio": info.get("trailingPE", "N/A"),
        "EPS": info.get("trailingEps", "N/A"),
        "Market Cap": info.get("marketCap", "N/A"),
        "Book Value": info.get("bookValue", "N/A"),
        "P/B Ratio": info.get("priceToBook", "N/A"),
        "Beta": info.get("beta", "N/A"),
        "52 Week High": info.get("fiftyTwoWeekHigh", "N/A"),
        "52 Week Low": info.get("fiftyTwoWeekLow", "N/A"),
        "52 Week Avg Price": (info.get("fiftyTwoWeekHigh", 0) + info.get("fiftyTwoWeekLow", 0)) / 2
    }
    for metric, value in metrics.items():
        st.write(f"**{metric}:** {value}")